### ISSUE TITLE
Default port in compose specifies TCP port

### ISSUE THREAD

**Issue by Oscar438** [mbround18/palworld-docker#8]
I noticed in the docs, the docker-compose file has the following port mapping: `8211:8211`  

Since palworld uses UDP, and compose treats unspecified protocols as TCP, should the compose file be this instead?
```yaml
version: "3.8"
services:
  palworld:
    ports:
      - "8211:8211/udp" # Default game port
      - "27015:27015/udp" # steam query port
```
